name: .NET Core (build)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@main
      with:
        # we need the submodule to zlib.managed.
        submodules: recursive

    - name: .NET core build
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Restore
      run: dotnet restore
      shell: bash

    - name: Build with dotnet
      run: |
        dotnet build --configuration Release --no-restore
        dotnet pack --configuration Release --no-build --no-restore
      shell: bash
