name: .NET Core (build pull request)

on: [pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # we need the submodule to zlib.managed.
        submodules: recursive
    - name: .NET core build
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    # we must build the msbuild task 1st in order to prevent build failures
    # due to ProjectReferencing it.
    - name: Build with dotnet
      run: |
        cd GitBuildInfo
        dotnet build --configuration Release
        cd ..
        dotnet build --configuration Release
    - name: Merge Dependabot
      uses: Elskom/merge-dependabot@v1.0
