name: .NET Core (build & publish pre-release)

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # we need the submodule to zlib.managed.
        submodules: recursive
    - name: .NET core build
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    # we must build the msbuild task 1st in order to prevent build failures
    # due to ProjectReferencing it.
    - name: Build with dotnet
      run: |
        cd GitBuildInfo
        dotnet build --configuration Release
        cd ..
        dotnet build --configuration Release
        dotnet pack --configuration Release --no-build
    # - name: Publish Pre-release
    #   id: publish_nuget
    #   uses: rohith/publish-nuget@v2
    #   with:
    #     # Filepath of the project to be packaged, relative to root of repository
    #     PROJECT_FILE_PATH: zlib.managed.csproj
    #     # Flag to toggle git tagging, enabled by default
    #     TAG_COMMIT: false
    #     # API key to authenticate with NuGet server
    #     NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    #     INCLUDE_SYMBOLS: true
