name: .NET Core (build pull request)

on: [pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # we need the submodule to zlib.managed.
        submodules: recursive
    - name: .NET core build
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
    # we must build the msbuild task 1st in order to prevent build failures
    # due to ProjectReferencing it.
    - name: Build with dotnet
      run: |
        cd GitBuildInfo
        dotnet build --configuration Release
        cd ..
        dotnet build --configuration Release
        dotnet pack --configuration Release --no-build

    - uses: hmarr/auto-approve-action@v2.0.0
      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' || github.actor == 'AraHaan' || github.actor == 'CatGirlsAreLife' || github.actor == 'Raitou' || github.actor == 'JunichiSama' || github.actor == 'xioke' || github.actor == 'Elskom-gitsync'
      with:
        # I think this must stay the same.
        github-token: "${{ secrets.GITHUB_TOKEN }}"
    - uses: actions-ecosystem/action-add-labels@v1
      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' || github.actor == 'AraHaan' || github.actor == 'CatGirlsAreLife' || github.actor == 'Raitou' || github.actor == 'JunichiSama' || github.actor == 'xioke' || github.actor == 'Elskom-gitsync'
      with:
        github_token: ${{ secrets.GITSYNC_TOKEN }}
        labels: |
          automerge

  submodule-update:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Wait on tests
      uses: lewagon/wait-on-check-action@master
      with:
        ref: ${{ github.sha }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10 # seconds
        running-workflow-name: submodule-update
        # wait on automerge to completely merge the pull request before
        # trying to create a new pull request in case it is not needed
        # at all.
        check-name: automerge
    - uses: actions/checkout@v2
      with:
        # we need the submodule to zlib.managed.
        submodules: recursive
    - name: Update submodule.
      run: git submodule update --remote
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITSYNC_TOKEN }}
        commit-message: Update zlib submodule.
        committer: GitHub <noreply@github.com>
        author: Elskom-gitsync <77945129+Elskom-gitsync@users.noreply.github.com>
        signoff: true
        branch: app/updated-submodules
        base: main
        delete-branch: true
        title: '[zlib.managed] Update submodule.'
        body: |
          Update report
          - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        labels: enhancement
        draft: false
