name: .NET Core (build & publish release)

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        # we need the submodule to zlib.managed.
        submodules: recursive
    - name: .NET core build
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: 6.0.100-preview.3.21202.5
    - name: Restore
      run: dotnet restore
      shell: bash
    # we must build the msbuild task 1st in order to prevent build failures
    # due to ProjectReferencing it.
    - name: Build with dotnet
      run: |
        dotnet build --configuration Release --no-restore
        dotnet pack --configuration Release --no-build
      shell: bash

    # - name: Publish Release
    #   id: publish_nuget
    #   uses: rohith/publish-nuget@v2
    #   with:
    #     # Filepath of the project to be packaged, relative to root of repository
    #     PROJECT_FILE_PATH: zlib.managed.csproj
    #     # Flag to toggle git tagging, enabled by default
    #     TAG_COMMIT: false
    #     # API key to authenticate with NuGet server
    #     NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    #     INCLUDE_SYMBOLS: true
