name: .NET Core (build & publish release)

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@main
      with:
        # we need the submodule to zlib.managed.
        submodules: recursive

    - name: .NET core build
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Restore
      run: dotnet restore
      shell: bash

    - name: Build with dotnet
      run: |
        dotnet build --configuration Release --no-restore
        dotnet pack --configuration Release --no-build --no-restore
      shell: bash

    - name: Publish Release
      id: publish_nuget
      uses: Elskom/publish-nuget@main
      with:
        # Filepath of the solution of which contains all the projects to be packed, relative to root of repository
        SOLUTION_FILE_PATH: build_all_packages.sln
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: '**/*.csproj'
        # Path to store all generated nuget packages, relative to root of repository
        PACKAGE_PATH: artifacts/
        # Flag to toggle git tagging, enabled by default
        TAG_COMMIT: false
        # API key to authenticate with NuGet server
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
        INCLUDE_SYMBOLS: false
